app/routes/agregar_paciente.py
from flask import Flask,render_template,Blueprint,session
"""
Funcion para agregar pacientes
"""
from app.extensions import db
from app.models.usuario import Pacientes

agregar_paciente_bp = Blueprint('agregar_paciente',__name__)

@agregar_paciente_bp.route('/agregar_pacientee')




def agregar_paciente_boton():
    
    user_name = ( db.session.query(Pacientes.nombre).filter(Pacientes.usuario_id == 4).scalar()) #el metodo filter permite concatenacion
    print(user_name)
    return render_template('agregar_paciente.html',user_name=user_name)


app/routes/contacto.py
from flask import Flask,Blueprint,render_template


contacto_bp = Blueprint('contacto', __name__, url_prefix="/contacto") #Nombres deben coincidir




@contacto_bp.route('/contacto/<nombre>')
def contacto(nombre):
    
    data= {
        'titulo':'Contacto',
        'nombre':nombre
    }
    return render_template('contacto.html',data=data)




app/routes/fase2.py
from flask import Flask,render_template,Blueprint,session,redirect,url_for,request
from app.utils.metricas import contar_pacientes




consulta_fase2_bp = Blueprint('consultafase2',__name__)


@consulta_fase2_bp.route('/consultafase2')
def consulta_fase_2():

    return render_template("ConsultaPhase2.html")

app/routes/home_page.py
from flask import Flask,Blueprint,render_template,request
home_bp = Blueprint('home_page',__name__, url_prefix="/home")



@home_bp.route('/')
def home_page():

    return render_template('home_page.html')





app/routes/main.py
from flask import Flask,render_template,Blueprint,session,redirect,url_for,request
from app.utils.metricas import contar_pacientes
"""
Nombre de la aplicacion NutriRecords Panel
"""

main_bp = Blueprint('main', __name__)

logout_bp = Blueprint('logout',__name__)

consulta_bp = Blueprint('consulta',__name__)
@main_bp.route('/')
def index():
    user_id = session.get('user')
    user_name = session.get('name')
    datos_home = {
        'total_pacientes': contar_pacientes()
    }
    if user_id and user_name:
        return render_template('home_page.html', user_id=user_id,user_name=user_name,datos_home = datos_home)
    
    else:
        return render_template( 'index.html')



@main_bp.route('/home/')
def home():
    return redirect(url_for('main.index'))

@main_bp.after_request
def no_cache(response):
    response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response

@logout_bp.route('/logout')
def logout_session():
    session.pop('user',None)
    return redirect(url_for('main.index'))

@consulta_bp.route('/consulta')
def modo_consulta():

    return render_template("ConsultaPhase1.html")

app/routes/register.py
from flask import Flask,render_template,Blueprint,request,session,redirect,url_for
from app.models.usuario import Usuario
from app.extensions import db
from app.utils.hashing import proteccion
from app.utils.comprobar_rol import comprobar_rol
register_bp = Blueprint('register', __name__)


@register_bp.route('/register',methods = ['GET','POST'])
def registrar_usuario_form():
    if request.method =='POST':
        nombre = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')
        telefono = request.form.get('telefono')

        user_id = ( db.session.query(Usuario.uid) .filter(Usuario.email == email) .scalar() )
        user_name = ( db.session.query(Usuario.nombre) .filter(Usuario.uid == user_id) .scalar() ) #el metodo filter permite concatenacion

        
        
        print(nombre,email,password,telefono)
        if not all([nombre, email, password, telefono]):
            return "Faltan campos obligatorios", 400
        password_hash = proteccion(password)
        nuevo_usuario = Usuario(
            nombre=nombre,
            email=email,
            contrasena=password_hash,
            telefono=telefono,
            rol=comprobar_rol(email)
            )
        db.session.add(nuevo_usuario)
        db.session.commit()
        session['user'] = user_id
        session['name'] = user_name
        return "Usuario registrado correctamente"
    return redirect(url_for('main.index'))
    
    


app/routes/sesion.py
from flask import Flask,render_template,Blueprint,request,session,redirect,url_for
from app.models.usuario import Usuario
from app.extensions import db
from app.utils.hashing import verificar_password


sesion_bp = Blueprint('sesion', __name__)


@sesion_bp.route('/login',methods = ['GET','POST'])
def verifica_sesion_form():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        usuario = Usuario.query.filter_by(email=email).first()
        user_id = ( db.session.query(Usuario.uid).filter(Usuario.email == email).scalar())
        user_name = ( db.session.query(Usuario.nombre) .filter(Usuario.uid == user_id).scalar())
        
        if not usuario:
            return 'Credenciales incorrectas'

        if verificar_password(password, usuario.contrasena):
            session['user'] = user_id
            session['name'] = user_name
            return redirect(url_for('main.index'))

    return render_template('login.html')
        

            


        

app/templates/ConsultaPhase1.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Paso 1</title>
    <link rel="stylesheet" href="static\css\ConsultaPhase1.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
</head>
<body>

<header class="topbar">
    <div class="logo">NutriRecords Panel</div>
    <div class="search">
        <input type="text" placeholder="Buscar...">
    </div>
    <div class="icons">
        <span>⬇</span>
        <span>⚙</span>
        <span>🔔</span>
    </div>
</header>

<main class="container">
    <section class="card">
        <h2>Datos del usuario</h2>

        <div class="grid-4">
            <input type="text" placeholder="Nombre del paciente">
            <input type="text" placeholder="Apellido">
            <input type="number" placeholder="Edad">
            <div class="group">
                <input type="number" placeholder="Peso">
                <input type="number" placeholder="Altura">
            </div>
        </div>

        <h3>Contacto:</h3>
        <div class="grid-4">
            <input type="email" placeholder="Correo electrónico">
            <input type="tel" placeholder="Teléfono">
            <input type="tel" placeholder="Teléfono 2">
            <input type="text" placeholder="Redes sociales">
        </div>

        <h3>Historial de Salud:</h3>
        <div class="grid-4">
            <div class="mini-card">
                <span>Enfermedades</span>
                <button>+</button>
            </div>
            <div class="mini-card">
                <span>Antecedentes familiares</span>
                <button>🔍</button>
            </div>
            <div class="mini-card">
                <span>Medicamentos</span>
                <button>+</button>
            </div>
            <div class="mini-card">
                <span>Alergias</span>
                <button>+</button>
            </div>
        </div>

        <h3>Datos adicionales:</h3>
        <div class="notes">
            <textarea placeholder="Notas..."></textarea>
        </div>

        <button class="primary"><a href="{{url_for('consultafase2.consulta_fase_2') }}">Siguiente</a></button>
    </section>
</main>

</body>
</html>



app/templates/ConsultaPhase2.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>NutriRecords – Fase 2</title>
    <link rel="stylesheet" href="static\css\ConsultaPhase2.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
</head>
<body>

<header class="topbar">
    <div class="logo">NutriRecords Panel</div>
    <div class="search">
        <input type="text" placeholder="Buscar...">
    </div>
    <div class="icons">
        <span>⬇</span>
        <span>⚙</span>
        <span>🔔</span>
    </div>
</header>

<main class="container">
    <section class="card">
        <div class="section-title">Datos alimenticios del paciente</div>

        <div class="layout">
            <!-- COLUMNA IZQUIERDA -->
            <div class="left">

                <label for = "Tipo_dieta " class="block-title">Tipo de dieta:</label>
                <select>
                    <option>Seleccionar dieta</option>
                    <option>Balanceada</option>
                    <option>Vegetariana</option>
                    <option>Vegana</option>
                    <option>Keto</option>
                </select>

                <label for="Preferencias" class="block-title">Preferencias de alimentos</label>
                <div class="chip-box">
                    <span class="chip">Lácteos ✕</span>
                    <span class="chip">Frutos secos ✕</span>
                    <span class="chip">Salchichas ✕</span>
                    <button class="add">Añadir +</button>
                </div>

                <label for="Rechazos" class="block-title">Alimentos que no gustan</label>
                <div class="chip-box">
                    <span class="chip">Pescado ✕</span>
                    <span class="chip">Chayote ✕</span>
                    <span class="chip">Pastas ✕</span>
                    <button class="add">Añadir +</button>
                </div>

                <label for= "Alergias" class="block-title">Alergias</label>
                <div class="chip-box">
                    <span class="chip">Mariscos ✕</span>
                    <span class="chip">Cacahuates ✕</span>
                    <span class="chip">Nuez ✕</span>
                    <button class="add">Añadir +</button>
                </div>

                <label for="Suplementos" class="block-title">Suplementos</label>
                <div class="chip-box">
                    <span class="chip">Vitamina B ✕</span>
                    <span class="chip">Vitamina C ✕</span>
                    <span class="chip">Complejo B ✕</span>
                    <button class="add">Añadir +</button>
                </div>

            </div>

            <!-- COLUMNA DERECHA -->
            <div class="right">
                <label  for="Horarios" class="block-title">Horarios de comida</label>

                <table>
                    <tr>
                        <th>Comida</th>
                        <th>Horario</th>
                    </tr>
                    <tr>
                        <td>Desayuno</td>
                        <td><input type="time" value="07:00"></td>
                    </tr>
                    <tr>
                        <td>Colación</td>
                        <td><input type="time" value="11:00"></td>
                    </tr>
                    <tr>
                        <td>Comida</td>
                        <td><input type="time" value="13:00"></td>
                    </tr>
                    <tr>
                        <td>Cena</td>
                        <td><input type="time"></td>
                    </tr>
                </table>

                <button class="primary">Siguiente</button>
            </div>
        </div>
    </section>
</main>

</body>
</html>

app/templates/agregar_paciente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agrega un paciente</title>
    <link rel="stylesheet" href="static\css\home.css" />
</head>
<body>
      <!-- TOP BAR -->
  <header class="topbar">
    <div class="logo">NutriRecords Panel</div>
    <div class="search">
      <input type="text" placeholder="Buscar paciente..." />
    </div>
    <div class="top-icons">⚙️ 🔔 ⬇️</div>
  </header>
  <div>
    pacientes disponibles:{{user_name}}

  </div>
</body>
</html>

app/templates/contacto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Inicio</title>
</head>
<body>
    <h1>{{data.nombre}}</h1>
</body>
</html>

app/templates/home_page.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>NutriRecords Panel</title>
    <link rel="stylesheet" href="static\css\home.css" />
</head>
<body>

  <!-- TOP BAR -->
  <header class="topbar">
    <div class="logo">NutriRecords Panel</div>
    <div class="search">
      <input type="text" placeholder="Buscar paciente..." />
    </div>
    <div class="top-icons">⚙️ 🔔 ⬇️</div>
  </header>

  <!-- CONTENT -->
  <div class="container">

    <section class="main">

      <!-- WELCOME -->
      <div class="welcome">
        <div>
          <h1>Buenos días, Dr. {{user_name}}</h1><button><a href="{{ url_for('logout.logout_session') }}">Cerrar sesion</a></button>
          <p>Hoy tienes 3 consultas programadas</p>
        </div>
        <button class="btn-primary"><a href="{{url_for('consulta.modo_consulta') }}">Modo consulta</a></button>
      </div>

      <!-- STATS -->
      <div class="stats">
        <div class="stat-card">
          <div>
            <strong>{{datos_home.total_pacientes}}</strong><br />
            <span>Pacientes activos</span>
          </div>
          <div class = "agrega-paciente"> <a href="{{ url_for('agregar_paciente.agregar_paciente_boton')}}">+</a>

          </div>
        </div>
        <div class="stat-card">
          <div>
            <strong>3</strong><br />
            <span>Consultas hoy</span>
          </div>
        </div>
        <div class="stat-card">
          <div>
            <strong>1</strong><br />
            <span>Casos críticos</span>
          </div>
        </div>
        <div class="stat-card">
          <div>
            <strong>1</strong><br />
            <span>Pacientes estancados</span>
          </div>
        </div>
      </div>

      <!-- CHART + NEXT -->
      <div class="grid-2">
        <div class="card">
          <h3>Progreso promedio de pacientes (6 meses)</h3>
          <div class="chart-placeholder"></div>
        </div>
        <div class="card">
          <h3>Próximas consultas</h3>
          <p>Paciente | Hora | Motivo de consulta</p>
        </div>
      </div>

      <!-- ACTIVITY + ACTIONS -->
      <div class="grid-2">
        <div class="card">
          <h3>Actividad reciente</h3>
          <ul>
            <li>Consultas completadas hoy</li>
            <li>Planes enviados</li>
            <li>Cambios de progreso</li>
          </ul>
        </div>
        <div class="card">
          <h3>Acciones rápidas</h3>
          <div class="actions">
            <button class="action-btn">📄 Historial</button>
            <button class="action-btn">➕ Nuevo paciente</button>
            <button class="action-btn">📤 Enviar plan rápido</button>
            <button class="action-btn">🗑️ Eliminar paciente</button>
          </div>
        </div>
      </div>

      <!-- PLANS -->
      <div class="card">
        <h3>Cumplimiento de planes (%)</h3>
        <div class="actions">
          <button class="action-btn">📝 Crear plan</button>
          <button class="action-btn">📚 Planes disponibles</button>
          <button class="action-btn">📊 Reportes</button>
        </div>
      </div>

    </section>

    <!-- SIDEBAR -->
    <aside class="sidebar">
      <div class="card">
        <h3>Avisos del sistema</h3>
        <div class="alert warning">Plan 1 no está siendo efectivo</div>
        <div class="alert danger">Plan 2 no está siendo cumplido</div>
        <div class="alert success">Plan 3 dio mejores resultados</div>
      </div>
    </aside>

  </div>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://kit.fontawesome.com/869dc8f5ef.js"
      crossorigin="anonymous"
    ></script>
    <title>login</title>
    <link rel="stylesheet" href="static\css\style.css" />
  </head>
  <body>
    <div class="container" id="container">
      <div class="form-container sign-up-container">
        <form action="{{url_for('register.registrar_usuario_form')}}" method="POST", autocomplete="off">
          <h1>Crea tu Cuenta</h1>
          <div class="social-container">
            <a href="#" class="social>">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#" class="social>">
              <i class="fab fa-google" id="red"></i>
            </a>
            <a href="#" class="social>">
              <i class="fab fa-linkedin-in"></i>
            </a>
          </div>
          <span>o usa tu email como registro</span>
          <input type="hidden" name="registro_id" value="registro">
          <input type="text" name ='name' placeholder="Name" />
          <input type="email" name ='email' placeholder="Email" />
          <input type="password" name='password' placeholder="Password" />
          <input type="text" name = 'telefono' placeholder="Telefono" />
          <button id="lila">Registrar</button>
        </form>
      </div>
      <div class="form-container sign-in-container">
        <form action="{{url_for('sesion.verifica_sesion_form')}}" method="POST", autocomplete="off">
          <h1>Iniciar Sesión</h1>
          <div class="social-container">
            <a href="#" class="social">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#" class="social>">
              <i class="fab fa-google" id="red2"></i>
            </a>
            <a href="#" class="social">
              <i class="fab fa-linkedin-in"></i>
            </a>
          </div>
          <span>o usa tu email</span>
          <input type="hidden" name="sesion_id " value="sesion">
          <input type="email" name ='email' placeholder="Email" />
          <input type="password" name='password' placeholder="Password" />
          <a href="#">Olvidaste tu contraseña?</a>
          <button>Iniciar sesión</button>
        </form>
      </div>
      <div class="overlay-container">
        <div class="overlay">
          <div class="overlay-panel overlay-left">
            <h1>¡Bienvenido!</h1>
            <p>
              Inicia sesión con tu cuenta
            </p>
            <button class="ghost" id="signIn">Inicia sesión</button>
          </div>
          <div class="overlay-panel overlay-right">
            <h1>Hola!!!</h1>
            <p>Crear tu cuenta</p>
            <button class="ghost" id="signUp">Registrar</button>
          </div>
        </div>
      </div>
    </div>

    <script src="static\scripts\app.js"></script>
  </body>
</html>